Repository cloudquery/plugin-pb-go, pull requests merged in 2023-11, with the labels that each got.

#151 fix: Add `unix://` to connection string for plugins from CloudQuery Hub
  managedplugin/plugin.go
Labels: automerge, fix

#153 fix(deps): Update module github.com/docker/docker to v24 [SECURITY]
  go.mod
  go.sum
  managedplugin/plugin.go
Labels: automerge, fix

#160 fix: Improve error messages when plugin download fails
  managedplugin/download.go
  managedplugin/download_test.go
  managedplugin/plugin_test.go
Labels: automerge, fix

#159 feat: Use and expose api url env variable
  managedplugin/download.go
Labels: automerge, feat

#158 feat: Validate hub download checksums
  go.mod
  go.sum
  managedplugin/download.go
Labels: feat

#171 fix: GitHub downloader should do a GET and retry, trying to discover the correct URL
  managedplugin/download.go
Labels: fix

#172 fix: Quality of life improvements
  .github/workflows/lint_golang.yml
  .golangci.yml
  go.mod
  managedplugin/download.go
  managedplugin/plugin.go
  managedplugin/registry_test.go
  specs/destination.go
  specs/destination_test.go
  specs/registry.go
  specs/registry_test.go
  specs/source.go
  specs/source_test.go
Labels: automerge, fix
