Repository cloudquery/plugin-pb-go, pull requests merged in 2023-06, with the labels that each got.

#13 fix: Embedded content handling with newlines
  specs/spec_reader.go
  specs/spec_reader_test.go
Labels: automerge, fix

#16 feat: Add managedplugin
  Makefile
  go.mod
  go.sum
  managedplugin/download.go
  managedplugin/download_test.go
  managedplugin/errors.go
  managedplugin/log_reader.go
  managedplugin/log_reader_test.go
  managedplugin/logging.go
  managedplugin/plugin.go
  managedplugin/plugin_test.go
  managedplugin/random.go
  managedplugin/registry.go
  managedplugin/registry_test.go
  managedplugin/unix.go
  managedplugin/windows.go
  pb/discovery/v1/discovery.pb.go
  pb/discovery/v1/discovery_grpc.pb.go
  specs/README.md
  specs/spec_reader.go
  specs/spec_reader_test.go
  specs/testdata/creds.txt
  specs/testdata/creds1.txt
  specs/testdata/creds2.json
  specs/testdata/dir/aws.yml
  specs/testdata/dir/postgresql.yml
  specs/testdata/dir_yaml/aws.yaml
  specs/testdata/dir_yaml/postgresql.yaml
  specs/testdata/env_variable_in_string.yml
  specs/testdata/env_variables.yml
  specs/testdata/gcp.yml
  specs/testdata/gcpv2.yml
  specs/testdata/multiple_sources.yml
  specs/testdata/number.txt
  specs/testdata/numbers.yml
Labels: automerge, feat

#19 chore(ci): Add Windows and MacOS tests
  .github/workflows/unittest.yml
Labels: automerge, ignore-for-release

#21 feat: Add Plugin Proto V3
  Makefile
  go.mod
  go.sum
  managedplugin/logging.go
  managedplugin/metrics.go
  managedplugin/plugin.go
  pb/discovery/v1/discovery.pb.go
  pb/plugin/v3/arrow.go
  pb/plugin/v3/arrow_test.go
  pb/plugin/v3/plugin.pb.go
  pb/plugin/v3/plugin_grpc.pb.go
Labels: automerge, feat

#24 fix: Discovery V1 regen
  pb/discovery/v1/discovery.pb.go
Labels: automerge, fix

#26 feat: Add arrow schema encoding to v2
  pb/destination/v1/arrow.go
  pb/source/v2/arrow.go
Labels: automerge, feat

#28 fix: Update schema encoding/deocoding in v2
  pb/destination/v1/arrow.go
  pb/source/v2/arrow.go
Labels: automerge, fix

#30 fix: Add Schemas encoding/decoding to plugin v3 proto
  pb/plugin/v3/arrow.go
  pb/plugin/v3/arrow_test.go
Labels: automerge, fix

#33 fix: Add record enc/dec to destv1 sourcev2
  pb/destination/v1/arrow.go
  pb/source/v2/arrow.go
Labels: fix

#35 fix: Regenerate V3, remove backend from proto
  pb/plugin/v3/plugin.pb.go
  pb/plugin/v3/plugin_grpc.pb.go
Labels: automerge, fix

#37 fix: Remove migrate_force from plugin v3
  pb/plugin/v3/plugin.pb.go
Labels: automerge, fix

#40 fix: Split Sync and Write messages to it's own proto messages
  pb/plugin/v3/plugin.pb.go
Labels: automerge, fix

#42 feat: Add migrate_force to Write.InsertMessage
  pb/plugin/v3/plugin.pb.go
Labels: feat

#45 fix: Add table_name to DeleteStale in proto v3
  pb/plugin/v3/plugin.pb.go
Labels: automerge, fix
