Repository cloudquery/plugin-pb-go, pull requests merged in 2023-07, with the labels that each got.

#56 fix: Add backend options to Sync in V3 proto
  pb/plugin/v3/plugin.pb.go
Labels: automerge, fix

#57 feat: Expose ConnectionString method in Client
  managedplugin/plugin.go
Labels: automerge, feat

#60 feat: Add local path validation
  managedplugin/plugin.go
  managedplugin/plugin_test.go
Labels: automerge, feat

#62 fix: Add `NoConnection` to init request
  pb/plugin/v3/plugin.pb.go
Labels: automerge, fix

#63 chore(ci): Add workflow to auto generate protocol code
  .github/workflows/regen.yml
Labels: automerge, ignore-for-release

#65 chore(ci): Install protoc before calling it
  .github/workflows/regen.yml
Labels: automerge, ignore-for-release

#70 feat: Docker registry
  go.mod
  go.sum
  managedplugin/docker.go
  managedplugin/plugin.go
  managedplugin/plugin_test.go
  managedplugin/registry.go
  specs/registry.go
Labels: automerge, feat

#72 fix: Wait for gRPC TCP connection in Docker registry
  managedplugin/plugin.go
Labels: automerge, fix
