Repository cloudquery/plugin-pb-go, pull requests merged in 2024-02, with the labels that each got.

#235 feat: Allow use of CloudQuery registry with docker plugins
  .github/workflows/unittest.yml
  managedplugin/download.go
  managedplugin/download_test.go
  managedplugin/hub.go
  managedplugin/options.go
  managedplugin/plugin.go
  managedplugin/plugin_test.go
Labels: automerge, feat

#243 fix: Tolerate non-JSON log lines from plugin
  managedplugin/plugin.go
Labels: fix

#245 fix: Ensure thread-safety of Metrics function
  managedplugin/plugin.go
Labels: automerge, fix

#246 feat: Allow managedplugins to control their environment
  managedplugin/plugin.go
Labels: automerge, feat

#248 feat: Support Private Docker Registries
  managedplugin/docker.go
  managedplugin/hub.go
  managedplugin/plugin.go
Labels: automerge, feat
