Repository cloudquery/plugin-pb-go, pull requests merged in 2024-08, with the labels that each got.

#383 chore: Add more govet lint rules
  .golangci.yml
Labels: automerge, ignore-for-release

#386 feat: Enable StateClients within Docker to connect to destinations
  managedplugin/options.go
  managedplugin/plugin.go
Labels: automerge, feat

#390 chore: Remove init of extra hosts.
  managedplugin/plugin.go
Labels: automerge, ignore-for-release

#389 refactor: Early return in case of a connection error
  managedplugin/plugin.go
Labels: automerge, refactor

#395 fix: Attempt to launch plugin up to 3 times
  managedplugin/plugin.go
Labels: automerge, fix
