Repository cloudquery/plugin-pb-go, pull requests merged in 2024-10, with the labels that each got.

#415 feat: Implement API to get latest plugin version.
  managedplugin/plugin.go
Labels: automerge, feat

#417 fix: Revert "fix(deps): Update module github.com/schollz/progressbar/v3 to v3.16.1 (#410)"
  go.mod
  go.sum
Labels: automerge, fix

#419 feat: Implement PluginVersionWarner to warn on outdated plugins.
  go.mod
  go.sum
  managedplugin/plugin.go
  managedplugin/version_checker.go
  managedplugin/version_checker_test.go
Labels: feat

#421 fix: Reset logger context when streaming logs from plugins
  managedplugin/logging.go
  managedplugin/plugin.go
Labels: automerge, fix

#423 feat: Link to latest version on 404 hub downloads
  managedplugin/download.go
  managedplugin/download_test.go
  managedplugin/hub.go
  managedplugin/plugin.go
Labels: automerge, feat
