Repository cloudquery/plugin-pb-go, pull requests merged in 2024-06, with the labels that each got.

#336 fix: Progressbar handling
  managedplugin/docker.go
  managedplugin/download.go
  managedplugin/download_test.go
  managedplugin/options.go
  managedplugin/plugin.go
Labels: fix

#338 fix: Revert "fix(deps): Update module github.com/schollz/progressbar/v3 to v3.14.3 (#330)"
  go.mod
  go.sum
Labels: automerge, fix

#341 feat: Expose if plugin was downloaded or cached
  managedplugin/download.go
  managedplugin/download_test.go
  managedplugin/metrics.go
  managedplugin/plugin.go
Labels: feat
