Repository cloudquery/plugin-pb-go, pull requests merged in 2024-07, with the labels that each got.

#357 chore: Switch to `googleapis/release-please-action`
  .github/workflows/release_pr.yml
Labels: automerge, ignore-for-release

#362 fix: Revert "fix(deps): Update module github.com/docker/docker to v27"
  go.mod
  go.sum
Labels: automerge, fix

#366 fix: Delete `invocation_id` log field when streaming plugins logs
  managedplugin/logging.go
Labels: automerge, fix

#369 feat: Add "transformer" plugin type.
  managedplugin/plugin.go
Labels: feat
